version: 2.1
orbs:
  hugo: circleci/hugo@0.2
  aws-s3: circleci/aws-s3@3.0

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - attach_workspace:
          at: site
      - aws-s3/sync:
          from: site/public
          to: s3://markpatricio-personal-web-statics

workflows:
  main:
    jobs:
      - hugo/build:
          html-proofer: true
          version: '0.55'
      - deploy:
          filters:
            branches:
              only: main
          requires:
            - hugo/build

# jobs:
#   build:
#     docker:
#       - image: cibuilds/hugo:latest
#     resource_class: small
#     working_directory: ~/hugo
#     environment:
#       HUGO_BUILD_DIR: ~/hugo/public
#       REGION: ap-southeast-2
#       BUCKET_NAME: markpatricio-personal-web-statics
#     steps:
#       - run: sudo apt-get update && sudo apt-get install -y --no-install-recommends git
#       - checkout
#       - run: git submodule sync && git submodule update --init
#       - run: curl -L https://github.com/bep/s3deploy/releases/download/v2.0.1/s3deploy_2.0.1_Linux-64bit.tar.gz | tar xvz
#       - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
#       - run: htmlproofer $HUGO_BUILD_DIR --allow-hash-href --check-html --empty-alt-ignore --disable-external
#       - deploy:
#           name: deploy
#           command: |
#             if [ "${CIRCLE_BRANCH}" = "main" ]; then
#               ./s3deploy -source=$HUGO_BUILD_DIR -region=$REGION -bucket=$BUCKET_NAME -path=/
#             else
#               echo "Not main branch, dry run only"
#             fi