version: 2.1
orbs:
  hugo: circleci/hugo@0.2
  aws-s3: circleci/aws-s3@3.0

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - attach_workspace:
          at: site
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: site/public
          to: s3://$S3_STATICS_BUCKET_NAME
      # awscli is setup by the aws-s3 orb already
      - run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

workflows:
  main:
    jobs:
      - hugo/build:
          html-proofer: true
          version: '0.55'
      - deploy:
          filters:
            branches:
              only: main
          requires:
            - hugo/build